name: CI/CD Docker

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Login GHCR
      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 3. Build Docker image
      - name: Build Docker
        run: docker build -t $IMAGE_NAME:latest .

      # ✅ 4. THÊM STEP NÀY
      - name: Run container test
        run: |
          docker run -e GithubAPI=${{ secrets.GithubAPI }} $IMAGE_NAME:latest

      # 5. Push Docker image
      - name: Push Docker
        run: docker push $IMAGE_NAME:latest